---
language: php

addons:
  apt:
    packages:
    - colordiff
    - elinks # For dysplaying php files on console.

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly


before_install:
- go get -u github.com/jingweno/ccat
- pip install --user pygments
- wget https://github.com/travis-util/https-security-checker/archive/master.zip --output-document=- | jar xvf /dev/stdin
- . https-security-checker-master/init-source.bash
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi


install:
- composer install
- composer run-script --list
- composer run-script -- symfony-skeleton --ansi

- composer create-project -vvv --no-install symfony/website-skeleton
- file website-skeleton/composer.lock
- composer --working-dir=website-skeleton config bin-dir bin
- composer --working-dir=website-skeleton -vvv install

before_script:
# - curl_security_check composer.lock
- curl_security_check website-skeleton/composer.lock
- curl_security_check skeleton/composer.lock
#^ This checks that the application doesn't use dependencies with known security vulnerabilities


script:
- composer --working-dir=website-skeleton exec --verbose -- console --ansi
- composer --working-dir=skeleton exec --verbose -- console --ansi


after_script:
- ls --almost-all --color
- ls --almost-all --color skeleton
- pygmentize -l sh -O linenos=1 skeleton/.env
- pygmentize -l sh -O linenos=1 skeleton/.env.dist
- ls --color skeleton/bin
- php -s skeleton/bin/console | elinks -force-html -dump-color-mode 4 -dump
- ls --almost-all --recursive --color skeleton/var
- ls --color skeleton/src
- ls --recursive --color skeleton/config


- composer --working-dir=website-skeleton update ocramius/proxy-manager # Looks almost like a bug in composer!
- composer --working-dir=website-skeleton show --latest
- composer --working-dir=website-skeleton show --latest > website-skeleton.txt
- composer --working-dir=skeleton show --latest
- composer --working-dir=skeleton show --latest > skeleton.txt
- composer --working-dir=website-skeleton why ocramius/proxy-manager
- composer --working-dir=skeleton why ocramius/proxy-manager
- composer --working-dir=website-skeleton why symfony/polyfill-ctype
- composer --working-dir=skeleton why symfony/polyfill-ctype
- colordiff --minimal --side-by-side website-skeleton.txt skeleton.txt
- $GOPATH/bin/ccat composer.json
- $GOPATH/bin/ccat website-skeleton/composer.json
- $GOPATH/bin/ccat skeleton/composer.json
- colordiff --minimal --side-by-side website-skeleton/composer.json skeleton/composer.json

- composer --working-dir=website-skeleton exec --list
- composer --working-dir=skeleton exec --list
- composer --working-dir=website-skeleton run-script --list
- composer --working-dir=skeleton run-script --list

- composer --working-dir=skeleton exec --verbose -- console list debug --ansi
- composer --working-dir=skeleton exec -vvv -- console --ansi
